<?php

declare(strict_types=1);

use Psalm\Internal\CodeLoader;
use Psalm\Internal\Cli\Psalm;

/**
 * Binary entry point for the TypePHP build: TypePHP requires a global main().
 *
 * `psalm-native --typephp-run <script.php> [args...]` runs an interpreted PHP
 * script on top of the compiled runtime instead of the Psalm CLI. The test
 * suite is run this way (see run-tests.php).
 *
 * @param list<string> $argv
 */
function main(int $argc, array $argv): void
{
    // class_alias() calls of vendor files (generated by gen-vendor-build.php)
    \Psalm\Internal\TypePhp\registerVendorClassAliases();
    if ($argc > 2 && $argv[1] === '--typephp-run') {
        CodeLoader::requireFile($argv[2]);
        return;
    }
    Psalm::run($argv);
}
