<?php

declare(strict_types=1);

namespace Psalm\Internal\Autoload;

use Psalm\Internal\CodeLoader;

use function array_values;
use function dirname;
use function file_exists;
use function is_array;
use function is_dir;
use function is_string;
use function ltrim;
use function spl_autoload_register;
use function str_starts_with;
use function strlen;
use function strrpos;
use function strtr;
use function substr;

use const DIRECTORY_SEPARATOR;

/**
 * Locates class files through the maps generated by Composer, without executing
 * the project's vendor/autoload.php.
 *
 * @internal
 */
final class ComposerClassLocator
{
    /**
     * @param array<string, list<string>> $psr4_prefixes
     * @param array<string, list<string>> $psr0_prefixes
     * @param array<string, string> $classmap
     * @param list<string> $autoload_files
     * @psalm-mutation-free
     */
    private function __construct(
        private readonly array $psr4_prefixes,
        private readonly array $psr0_prefixes,
        private readonly array $classmap,
        private readonly array $autoload_files,
    ) {
    }

    /**
     * @param string $autoload_file path to a Composer generated vendor/autoload.php
     */
    public static function fromAutoloadFile(string $autoload_file): ?self
    {
        $composer_dir = dirname($autoload_file) . DIRECTORY_SEPARATOR . 'composer';

        if (!is_dir($composer_dir)) {
            return null;
        }

        return new self(
            self::readPrefixMap($composer_dir . DIRECTORY_SEPARATOR . 'autoload_psr4.php'),
            self::readPrefixMap($composer_dir . DIRECTORY_SEPARATOR . 'autoload_namespaces.php'),
            self::readStringMap($composer_dir . DIRECTORY_SEPARATOR . 'autoload_classmap.php'),
            array_values(self::readStringMap($composer_dir . DIRECTORY_SEPARATOR . 'autoload_files.php')),
        );
    }

    /**
     * @return array<string, list<string>>
     */
    private static function readPrefixMap(string $file): array
    {
        if (!file_exists($file)) {
            return [];
        }

        $map = [];

        /** @psalm-suppress MixedAssignment */
        foreach (ComposerAutoloadFileEvaluator::evaluate($file) as $prefix => $dirs) {
            $list = [];

            /** @psalm-suppress MixedAssignment */
            foreach (is_array($dirs) ? $dirs : [$dirs] as $dir) {
                if (is_string($dir)) {
                    $list[] = $dir;
                }
            }

            $map[(string) $prefix] = $list;
        }

        return $map;
    }

    /**
     * @return array<string, string>
     */
    private static function readStringMap(string $file): array
    {
        if (!file_exists($file)) {
            return [];
        }

        $map = [];

        /** @psalm-suppress MixedAssignment */
        foreach (ComposerAutoloadFileEvaluator::evaluate($file) as $key => $value) {
            if (is_string($value)) {
                $map[(string) $key] = $value;
            }
        }

        return $map;
    }

    /**
     * @return array<string, list<string>>
     */
    public function getPrefixesPsr4(): array
    {
        return $this->psr4_prefixes;
    }

    /**
     * Files that Composer would include on every request (the "files" autoload entries).
     *
     * @return list<string>
     */
    public function getAutoloadFiles(): array
    {
        return $this->autoload_files;
    }

    /**
     * @return string|false
     */
    public function findFile(string $class): string|bool
    {
        $class = ltrim($class, '\\');

        if (isset($this->classmap[$class])) {
            return $this->classmap[$class];
        }

        foreach ($this->psr4_prefixes as $prefix => $dirs) {
            if ($prefix !== '' && !str_starts_with($class, $prefix)) {
                continue;
            }

            $relative_path = strtr(substr($class, strlen($prefix)), '\\', DIRECTORY_SEPARATOR) . '.php';

            foreach ($dirs as $dir) {
                $file = $dir . DIRECTORY_SEPARATOR . $relative_path;

                if (file_exists($file)) {
                    return $file;
                }
            }
        }

        $namespace_end = strrpos($class, '\\');

        if ($namespace_end !== false) {
            $psr0_path = strtr(substr($class, 0, $namespace_end + 1), '\\', DIRECTORY_SEPARATOR)
                . strtr(substr($class, $namespace_end + 1), '_', DIRECTORY_SEPARATOR) . '.php';
        } else {
            $psr0_path = strtr($class, '_', DIRECTORY_SEPARATOR) . '.php';
        }

        foreach ($this->psr0_prefixes as $prefix => $dirs) {
            if ($prefix !== '' && !str_starts_with($class, $prefix)) {
                continue;
            }

            foreach ($dirs as $dir) {
                $file = $dir . DIRECTORY_SEPARATOR . $psr0_path;

                if (file_exists($file)) {
                    return $file;
                }
            }
        }

        return false;
    }

    /**
     * Makes the located classes loadable (only where runtime code loading is available).
     */
    public function register(): void
    {
        if (!CodeLoader::canLoadCode()) {
            return;
        }

        spl_autoload_register(function (string $class): void {
            $file = $this->findFile($class);

            if ($file !== false) {
                CodeLoader::requireFileOnce($file);
            }
        });
    }
}
