<?php // phpcs:ignoreFile

/**
 * Generated by bin/generate-dictionaries.php from dictionaries/InternalTaintSinkMap.php - do not edit.
 */

declare(strict_types=1);

namespace Psalm\Internal\Dictionaries;

/**
 * @internal
 */
final class InternalTaintSinkMap
{
    /** base64 encoded, gzip compressed JSON */
    public const DATA = <<<'DATA'
H4sIAAAAAAACE3VUyW7DIBD9l5x9cJxFqX+lqhDFExuFrSxt3ar/3sExMTjyxdK8DRgG/+7gG9iufW1O57dqxyxQD+QaFPNcK8Tr6oL4lQsgPXjCtPKgvENm
fzqcE2VCSdXNMVLagFrKoARXt6Vm2oxzTpUcGLYIMnkSyFvH7aKQ+hNIMELTDjqSuZPeUOuAcMVJGc0G/ZVtTaxqbENXGiwoKtfpVha7GdAFsT7WL7E1bpTl
iT1IgzELwPt3rqgdSVAOLKeC/8Q1mriljhrigFo2TNewxybFUDm6D8HJRwA7TsSheaBtm+AMJHgYsaUvuNwkg/Cbq5RkbjMWsOXwbFmIXO689G1L4uw4bwPz
a+Ok2Eqd7atoQ53zgw2PoTZMeUGKOTd9qudABPJFMhQnGy8RCumqLQkh6KfSFYQD1W1ET9Rz1AKXeVUdRwo80/rGpympj5cqfiI+gFid0Y0O5+1RPk+YmZ/n
3BKrGSkQFqyITydeymnfJAS3oI2fz3LH8c/AJe3B3cMj+PcPWdylcFoEAAA=
DATA;
}
