<?php
// apply.php <jsonl> [--dry]: applies the plugin's edits (each call site's edits atomically; overlapping or duplicate
// sites once), adds missing Sym constants, and prints a summary of the skipped sites by argument shape.
declare(strict_types=1);
$in = $argv[1] ?? exit("usage: apply.php out.jsonl [--dry]\n");
$dry = in_array('--dry', $argv, true);
$sites = []; $syms = []; $skips = []; $errors = 0;
foreach (file($in, FILE_IGNORE_NEW_LINES) as $line) {
    $r = json_decode($line, true);
    if ($r['kind'] === 'edit') { $sites[$r['file']][$r['site'] . json_encode($r['edits'])] = $r['edits']; }
    elseif ($r['kind'] === 'sym') { $syms[$r['name']] = $r['value']; }
    elseif ($r['kind'] === 'skip') { $skips[$r['site']] = $r['args']; }
    else { $errors++; }
}
$n = 0;
foreach ($sites as $file => $group) {
    $edits = [];
    foreach ($group as $site_edits) { foreach ($site_edits as $e) { $edits[$e[0] . ':' . $e[1]] = $e; } }
    usort($edits, fn($a, $b) => $b[0] <=> $a[0]);
    $src = file_get_contents($file); $prev = PHP_INT_MAX;
    foreach ($edits as [$s, $e, $t]) {
        if ($e > $prev) { fwrite(STDERR, "overlap in $file at $s\n"); continue; }
        $src = substr($src, 0, $s) . $t . substr($src, $e); $prev = $s; $n++;
    }
    // the Sym import, in alphabetical position among the use statements
    if (str_contains($src, 'Sym::') && !preg_match('/^use Psalm\\\\Internal\\\\Sym;$/m', $src)
        && !preg_match('/^namespace Psalm\\\\Internal;$/m', $src)
    ) {
        $line = "use Psalm\\Internal\\Sym;";
        preg_match_all('/^use [A-Z][^;(]*;$/m', $src, $m, PREG_OFFSET_CAPTURE);
        $at = null;
        foreach ($m[0] as [$u, $off]) {
            if (strcmp($u, $line) > 0 && !str_starts_with($u, 'use function') && !str_starts_with($u, 'use const')) { $at = $off; break; }
        }
        if ($at === null) {
            $last = null;
            foreach ($m[0] as [$u, $off]) { if (!str_starts_with($u, 'use function') && !str_starts_with($u, 'use const')) { $last = $off + strlen($u) + 1; } }
            $at = $last ?? (strpos($src, "\n", strpos($src, 'namespace ')) + 1);
        }
        $src = substr($src, 0, $at) . $line . "\n" . substr($src, $at);
    }
    if (!$dry) { file_put_contents($file, $src); }
}
$symfile = __DIR__ . '/../../src/Psalm/Internal/Sym.php';
$sym_src = file_get_contents($symfile); $added = 0;
foreach ($syms as $name => $value) {
    if (preg_match('/const ' . preg_quote($name) . '\b/', $sym_src)) { continue; }
    $pos = strrpos($sym_src, '}');
    $sym_src = substr($sym_src, 0, $pos) . "\n    /** generated by tools/id-refactor */\n    public const $name = $value;\n" . substr($sym_src, $pos);
    $added++;
}
if (!$dry && $added) { file_put_contents($symfile, $sym_src); }
$shapes = [];
foreach ($skips as $site => $args) { foreach ($args as $a) { $shapes[($a['node'] ?? $a['why']) . ' : ' . ($a['type'] ?? '')][] = $site; } }
uasort($shapes, fn($a, $b) => count($b) <=> count($a));
printf("files %d, edits %d, sym constants added %d, skipped sites %d, plugin errors %d\n", count($sites), $n, $added, count($skips), $errors);
foreach (array_slice($shapes, 0, 25, true) as $shape => $list) { printf("%5d  %s   e.g. %s\n", count($list), $shape, $list[0]); }
