#!/usr/bin/env php
<?php

namespace Psalm;

use Psalm\Internal\Cli\Refactor;

require_once __DIR__ . '/src/Psalm/Internal/Cli/Refactor.php';
require_once __DIR__ . '/src/Psalm/IssueBuffer.php';
require_once __DIR__ . '/src/Psalm/Internal/ErrorHandler.php';
require_once __DIR__ . '/src/Psalm/Internal/CliUtils.php';
require_once __DIR__ . '/src/Psalm/Internal/Composer.php';
require_once __DIR__ . '/src/Psalm/Internal/IncludeCollector.php';
Refactor::run($argv);
