#!/usr/bin/env php
<?php

namespace Psalm;

use Psalm\Internal\Cli\LanguageServer;

require_once __DIR__ . '/src/Psalm/Internal/Cli/LanguageServer.php';
require_once __DIR__ . '/src/Psalm/Internal/LanguageServer/ClientConfiguration.php';
require_once __DIR__ . '/src/Psalm/Internal/ErrorHandler.php';
require_once __DIR__ . '/src/Psalm/Internal/CliUtils.php';
require_once __DIR__ . '/src/Psalm/Internal/Composer.php';
require_once __DIR__ . '/src/Psalm/Internal/IncludeCollector.php';
LanguageServer::run($argv);
