<?php

declare(strict_types=1);

namespace Psalm\Internal\Codebase;

use function array_key_exists;
use function dirname;

/**
 * The internal constants of the PHP the analyzer models (dictionaries/ConstantMap.php, generated by
 * bin/generate-constant-map.php): Psalm read get_defined_constants() of its own runtime instead, which the
 * compiled program does not have.
 *
 * @internal
 */
final class ConstantMap
{
    /** @var array<string, scalar|null>|null */
    private static ?array $map = null;

    /**
     * @return array<string, scalar|null>
     */
    public static function get(): array
    {
        if (self::$map === null) {
            self::$map = require(dirname(__DIR__, 4) . '/dictionaries/ConstantMap.php');
        }
        return self::$map;
    }

    public static function has(string $name): bool
    {
        return array_key_exists($name, self::get());
    }
}
