<?php
/**
 * Generates src/Psalm/Internal/Sym.php: the interned ids of the names Psalm's own code refers to (pzoom's
 * generated `StrId` constants). Run after changing the list below.
 */

declare(strict_types=1);

require __DIR__ . '/../src/Psalm/Internal/Interner.php';

use Psalm\Internal\Interner;

$names = [
    // NAMES
];

$seen = [];
foreach ($names as $const => $name) {
    if (isset($seen[$name])) {
        fwrite(STDERR, "duplicate preloaded name: $name\n");
        exit(1);
    }
    $seen[$name] = true;
}

$out = "<?php\n\ndeclare(strict_types=1);\n\nnamespace Psalm\\Internal;\n\n/**\n * The interned ids (Interner::hash) of the names Psalm's own code refers to: pzoom's generated `StrId`\n * constants. Generated by bin/generate-sym.php; do not edit.\n *\n * @internal\n * @psalm-immutable\n */\nfinal class Sym\n{\n";
foreach ($names as $const => $name) {
    $out .= sprintf("    /** `%s` */\n    public const %s = %d;\n", str_replace('*/', '*\\/', $name), $const, Interner::hash($name));
}
$out .= "\n    /**\n     * The preloaded names, interned at startup so their ids resolve in every process.\n     *\n     * @var list<string>\n     */\n    public const PRELOADED = [\n";
foreach ($names as $name) {
    $out .= "        " . var_export($name, true) . ",\n";
}
$out .= "    ];\n}\n";

file_put_contents(__DIR__ . '/../src/Psalm/Internal/Sym.php', $out);
echo "wrote " . count($names) . " constants\n";
