//! Pre-compiled data files: the value returned by a `<?php return [...];` file, as a static table
//! generated by the transpiler. `include`/`require` of such a file yields `Data::to_mixed()`.

use crate::key::ArrayKey;
use crate::map::Map;
use crate::mixed::Mixed;
use crate::string::Str;

pub enum DataKey {
    Int(i64),
    Str(&'static str),
    Bytes(&'static [u8]),
}

pub enum Data {
    Null,
    Bool(bool),
    Int(i64),
    Float(f64),
    Str(&'static str),
    Bytes(&'static [u8]),
    Arr(&'static [(DataKey, Data)]),
}

impl DataKey {
    fn to_key(&self) -> ArrayKey {
        match self {
            DataKey::Int(i) => ArrayKey::Int(*i),
            DataKey::Str(s) => ArrayKey::from_str_val(Str::from_static(s)),
            DataKey::Bytes(b) => ArrayKey::from_str_val(Str::from_bytes(b)),
        }
    }
}

impl Data {
    pub fn to_mixed(&self) -> Mixed {
        match self {
            Data::Null => Mixed::Null,
            Data::Bool(b) => Mixed::Bool(*b),
            Data::Int(i) => Mixed::Int(*i),
            Data::Float(f) => Mixed::Float(*f),
            Data::Str(s) => Mixed::Str(Str::from_static(s)),
            Data::Bytes(b) => Mixed::Str(Str::from_bytes(b)),
            Data::Arr(items) => {
                let mut m: Map<ArrayKey, Mixed> = Map::new();
                for (k, v) in items.iter() {
                    m.insert(k.to_key(), v.to_mixed());
                }
                Mixed::Arr(m)
            }
        }
    }
}
