//! Pre-compiled data files: the value returned by a `<?php return [...];` file, as a static table
//! generated by the transpiler. `include`/`require` of such a file yields `Data::to_mixed()`.

use crate::key::{ArrayKey, MapKey};
use crate::list::List;
use crate::map::Map;
use crate::mixed::Mixed;
use crate::string::Str;

pub enum DataKey {
    Int(i64),
    Str(&'static str),
    Bytes(&'static [u8]),
}

pub enum Data {
    Null,
    Bool(bool),
    Int(i64),
    Float(f64),
    Str(&'static str),
    Bytes(&'static [u8]),
    Arr(&'static [(DataKey, Data)]),
}

impl DataKey {
    fn to_key(&self) -> ArrayKey {
        match self {
            DataKey::Int(i) => ArrayKey::Int(*i),
            DataKey::Str(s) => ArrayKey::from_str_val(Str::from_static(s)),
            DataKey::Bytes(b) => ArrayKey::from_str_val(Str::from_bytes(b)),
        }
    }
}

impl Data {
    pub fn to_mixed(&self) -> Mixed {
        match self {
            Data::Null => Mixed::Null,
            Data::Bool(b) => Mixed::Bool(*b),
            Data::Int(i) => Mixed::Int(*i),
            Data::Float(f) => Mixed::Float(*f),
            Data::Str(s) => Mixed::Str(Str::from_static(s)),
            Data::Bytes(b) => Mixed::Str(Str::from_bytes(b)),
            Data::Arr(items) => {
                let mut m: Map<ArrayKey, Mixed> = Map::new();
                for (k, v) in items.iter() {
                    m.insert(k.to_key(), v.to_mixed());
                }
                Mixed::Arr(m)
            }
        }
    }
}

impl Data {
    /// The value under a string key of an array (None for other keys and non-arrays).
    pub fn get(&self, key: &str) -> Option<&Data> {
        match self {
            Data::Arr(items) => items
                .iter()
                .find(|(k, _)| match k {
                    DataKey::Str(s) => *s == key,
                    DataKey::Bytes(b) => *b == key.as_bytes(),
                    DataKey::Int(_) => false,
                })
                .map(|(_, v)| v),
            _ => None,
        }
    }

    /// The value under an integer key of an array.
    pub fn get_index(&self, index: i64) -> Option<&Data> {
        match self {
            Data::Arr(items) => items
                .iter()
                .find(|(k, _)| matches!(k, DataKey::Int(i) if *i == index))
                .map(|(_, v)| v),
            _ => None,
        }
    }
}

/// A typed value read out of a data table (the type the including site declares).
pub trait FromData: Sized {
    fn from_data(d: &Data) -> Self;
}

/// A typed map key read out of a data table.
pub trait FromDataKey: Sized {
    fn from_data_key(k: &DataKey) -> Self;
}

impl FromData for i64 {
    fn from_data(d: &Data) -> Self {
        match d {
            Data::Int(i) => *i,
            Data::Float(f) => *f as i64,
            Data::Bool(b) => *b as i64,
            Data::Null => 0,
            Data::Str(s) => crate::conv::str_to_int(s.as_bytes()),
            Data::Bytes(b) => crate::conv::str_to_int(b),
            Data::Arr(_) => panic!("data: an int was declared where the table holds an array"),
        }
    }
}
impl FromData for f64 {
    fn from_data(d: &Data) -> Self {
        match d {
            Data::Float(f) => *f,
            Data::Int(i) => *i as f64,
            Data::Bool(b) => *b as i64 as f64,
            Data::Null => 0.0,
            Data::Str(s) => crate::conv::str_to_float(s.as_bytes()),
            Data::Bytes(b) => crate::conv::str_to_float(b),
            Data::Arr(_) => panic!("data: a float was declared where the table holds an array"),
        }
    }
}
impl FromData for bool {
    fn from_data(d: &Data) -> Self {
        match d {
            Data::Bool(b) => *b,
            Data::Int(i) => *i != 0,
            Data::Float(f) => *f != 0.0,
            Data::Null => false,
            Data::Str(s) => !s.is_empty() && *s != "0",
            Data::Bytes(b) => !b.is_empty() && *b != b"0",
            Data::Arr(items) => !items.is_empty(),
        }
    }
}
impl FromData for Str {
    fn from_data(d: &Data) -> Self {
        match d {
            Data::Str(s) => Str::from_static(s),
            Data::Bytes(b) => Str::from_bytes(b),
            Data::Int(i) => crate::traits::ToStr::to_php_str(i),
            Data::Float(f) => crate::traits::ToStr::to_php_str(f),
            Data::Bool(b) => crate::traits::ToStr::to_php_str(b),
            Data::Null => Str::from_static(""),
            Data::Arr(_) => panic!("data: a string was declared where the table holds an array"),
        }
    }
}
impl FromData for () {
    fn from_data(_d: &Data) -> Self {}
}
impl FromData for ArrayKey {
    fn from_data(d: &Data) -> Self {
        match d {
            Data::Int(i) => ArrayKey::Int(*i),
            other => ArrayKey::from_str_val(Str::from_data(other)),
        }
    }
}
impl FromData for Mixed {
    fn from_data(d: &Data) -> Self {
        d.to_mixed()
    }
}
impl<T: FromData> FromData for Option<T> {
    fn from_data(d: &Data) -> Self {
        match d {
            Data::Null => None,
            other => Some(T::from_data(other)),
        }
    }
}
impl<T: FromData + Clone> FromData for List<T> {
    fn from_data(d: &Data) -> Self {
        match d {
            Data::Arr(items) => List::from_vec(items.iter().map(|(_, v)| T::from_data(v)).collect()),
            Data::Null => List::new(),
            _ => panic!("data: a list was declared where the table holds a scalar"),
        }
    }
}
impl<K: FromDataKey + MapKey, V: FromData + Clone> FromData for Map<K, V> {
    fn from_data(d: &Data) -> Self {
        let mut m: Map<K, V> = Map::new();
        match d {
            Data::Arr(items) => {
                for (k, v) in items.iter() {
                    m.insert(K::from_data_key(k), V::from_data(v));
                }
            }
            Data::Null => {}
            _ => panic!("data: a map was declared where the table holds a scalar"),
        }
        m
    }
}
impl FromDataKey for i64 {
    fn from_data_key(k: &DataKey) -> Self {
        match k {
            DataKey::Int(i) => *i,
            DataKey::Str(s) => crate::conv::str_to_int(s.as_bytes()),
            DataKey::Bytes(b) => crate::conv::str_to_int(b),
        }
    }
}
impl FromDataKey for Str {
    fn from_data_key(k: &DataKey) -> Self {
        match k {
            DataKey::Int(i) => crate::traits::ToStr::to_php_str(i),
            DataKey::Str(s) => Str::from_static(s),
            DataKey::Bytes(b) => Str::from_bytes(b),
        }
    }
}
impl FromDataKey for ArrayKey {
    fn from_data_key(k: &DataKey) -> Self {
        k.to_key()
    }
}

macro_rules! from_data_tuple {
    ($($n:tt $t:ident),+) => {
        impl<$($t: FromData),+> FromData for ($($t,)+) {
            fn from_data(d: &Data) -> Self {
                ($($t::from_data(d.get_index($n).unwrap_or(&Data::Null)),)+)
            }
        }
    };
}
from_data_tuple!(0 A);
from_data_tuple!(0 A, 1 B);
from_data_tuple!(0 A, 1 B, 2 C);
from_data_tuple!(0 A, 1 B, 2 C, 3 D);
from_data_tuple!(0 A, 1 B, 2 C, 3 D, 4 E);
from_data_tuple!(0 A, 1 B, 2 C, 3 D, 4 E, 5 F);
from_data_tuple!(0 A, 1 B, 2 C, 3 D, 4 E, 5 F, 6 G);
from_data_tuple!(0 A, 1 B, 2 C, 3 D, 4 E, 5 F, 6 G, 7 H);
