//! `TokenKind` — a semantic PHP token enum (mago-style), decoupled from PHP's numeric `T_*`
//! constant values. The tokenizer emits these; the parser bridge maps each to its grammar symbol.
//!
//! Adopting an enum (instead of the numeric `T_*` ids) removes a whole class of bugs: the
//! transpiler used to inline the *host* PHP token-constant values for `\T_*` references while
//! php-rt's tokenizer + the parser tables used a *different* numeric scheme, so e.g. a by-reference
//! `&` (php-rt `T_AMPERSAND_FOLLOWED` = 409) collided with host `T_BAD_CHARACTER` = 409 and every
//! `&$var` was rejected as "Unexpected character &". With a by-name enum there are no numbers to
//! disagree on. Variant set mirrors carthage-software/mago's `TokenKind`.

/// A PHP lexical token kind. `&` disambiguation (by-ref vs bitwise vs intersection) is the parser's
/// job via lookahead, so there is a single `Ampersand` here (unlike PHP's `T_AMPERSAND_*` split).
#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug, PartialOrd, Ord)]
#[repr(u16)]
pub enum TokenKind {
    Whitespace,
    Eval,
    Die,
    Self_,
    Parent,
    Backtick,
    DocumentStart,
    DocumentEnd,
    From,
    Print,
    Dollar,
    HaltCompiler,
    Readonly,
    Global,
    Abstract,
    Ampersand,
    AmpersandEqual,
    AmpersandAmpersand,
    AmpersandAmpersandEqual,
    Array,
    ArrayCast,
    MinusGreaterThan,
    QuestionMinusGreaterThan,
    At,
    As,
    Asterisk,
    HashLeftBracket,
    Bang,
    BangEqual,
    LessThanGreaterThan,
    BangEqualEqual,
    LessThanEqualGreaterThan,
    BoolCast,
    BooleanCast,
    And,
    Or,
    Break,
    Callable,
    Caret,
    CaretEqual,
    Case,
    Catch,
    Class,
    ClassConstant,
    TraitConstant,
    FunctionConstant,
    MethodConstant,
    LineConstant,
    FileConstant,
    Clone,
    MinusEqual,
    CloseTag,
    QuestionQuestion,
    QuestionQuestionEqual,
    AsteriskEqual,
    Colon,
    Comma,
    SingleLineComment,
    HashComment,
    MultiLineComment,
    DocBlockComment,
    Const,
    PartialLiteralString,
    LiteralString,
    Continue,
    Declare,
    MinusMinus,
    Default,
    DirConstant,
    SlashEqual,
    Do,
    DollarLeftBrace,
    Dot,
    DotEqual,
    EqualGreaterThan,
    DoubleCast,
    RealCast,
    FloatCast,
    ColonColon,
    EqualEqual,
    DoubleQuote,
    Else,
    Echo,
    DotDotDot,
    ElseIf,
    Empty,
    EndDeclare,
    EndFor,
    EndForeach,
    EndIf,
    EndSwitch,
    EndWhile,
    Enum,
    Equal,
    Extends,
    False,
    Final,
    Finally,
    LiteralFloat,
    Fn,
    For,
    Foreach,
    FullyQualifiedIdentifier,
    Function,
    Goto,
    GreaterThan,
    GreaterThanEqual,
    Identifier,
    If,
    Implements,
    Include,
    IncludeOnce,
    PlusPlus,
    InlineText,
    InlineShebang,
    Instanceof,
    Insteadof,
    Exit,
    Unset,
    Isset,
    List,
    LiteralInteger,
    OffsetNumber,
    OffsetString,
    IntCast,
    IntegerCast,
    Interface,
    LeftBrace,
    LeftBracket,
    LeftParenthesis,
    LeftShift,
    LeftShiftEqual,
    RightShift,
    RightShiftEqual,
    LessThan,
    LessThanEqual,
    Match,
    Minus,
    Namespace,
    NamespaceSeparator,
    NamespaceConstant,
    PropertyConstant,
    New,
    Null,
    ObjectCast,
    UnsetCast,
    OpenTag,
    EchoTag,
    ShortOpenTag,
    Percent,
    PercentEqual,
    Pipe,
    PipeEqual,
    Plus,
    PlusEqual,
    AsteriskAsterisk,
    AsteriskAsteriskEqual,
    Private,
    PrivateSet,
    Protected,
    ProtectedSet,
    Public,
    PublicSet,
    QualifiedIdentifier,
    Question,
    Require,
    RequireOnce,
    Return,
    RightBrace,
    RightBracket,
    RightParenthesis,
    Semicolon,
    Slash,
    Static,
    StringCast,
    BinaryCast,
    VoidCast,
    StringPart,
    StringVariableName,
    Switch,
    Throw,
    Trait,
    EqualEqualEqual,
    True,
    Try,
    Use,
    Var,
    Variable,
    Yield,
    While,
    Tilde,
    PipePipe,
    Xor,
    PipeGreaterThan,
    BadCharacter, // a character the lexer could not tokenize (PHP `T_BAD_CHARACTER`)
}

impl Default for TokenKind {
    #[inline]
    fn default() -> Self {
        TokenKind::Whitespace
    }
}

use crate::consts as c;

/// Classify one token produced by [`crate::tokenizer::tokenize`] (php-rt's internal numeric id +
/// text) into its semantic [`TokenKind`]. This is the boundary that lets everything downstream use
/// the enum instead of the numeric `T_*` scheme. `&` is a single [`TokenKind::Ampersand`] — the
/// parser bridge disambiguates by-ref/bitwise/intersection via lookahead.
pub fn classify(id: i64, text: &[u8]) -> TokenKind {
    use TokenKind as K;
    // single-character punctuation tokens carry their byte value as the id (see `emit_char`)
    match id {
        33 => return K::Bang,
        36 => return K::Dollar,
        37 => return K::Percent,
        38 => return K::Ampersand,
        40 => return K::LeftParenthesis,
        41 => return K::RightParenthesis,
        42 => return K::Asterisk,
        43 => return K::Plus,
        44 => return K::Comma,
        45 => return K::Minus,
        46 => return K::Dot,
        47 => return K::Slash,
        58 => return K::Colon,
        59 => return K::Semicolon,
        60 => return K::LessThan,
        61 => return K::Equal,
        62 => return K::GreaterThan,
        63 => return K::Question,
        64 => return K::At,
        91 => return K::LeftBracket,
        93 => return K::RightBracket,
        94 => return K::Caret,
        96 => return K::Backtick,
        123 => return K::LeftBrace,
        124 => return K::Pipe,
        125 => return K::RightBrace,
        126 => return K::Tilde,
        34 => return K::DoubleQuote,
        _ => {}
    }
    // multi-character / named tokens, matched by php-rt's constant (value-robust)
    match id {
        x if x == c::T_LNUMBER => K::LiteralInteger,
        x if x == c::T_DNUMBER => K::LiteralFloat,
        x if x == c::T_STRING => K::Identifier,
        x if x == c::T_NAME_FULLY_QUALIFIED => K::FullyQualifiedIdentifier,
        x if x == c::T_NAME_RELATIVE => K::QualifiedIdentifier,
        x if x == c::T_NAME_QUALIFIED => K::QualifiedIdentifier,
        x if x == c::T_VARIABLE => K::Variable,
        x if x == c::T_INLINE_HTML => K::InlineText,
        x if x == c::T_ENCAPSED_AND_WHITESPACE => K::StringPart,
        x if x == c::T_CONSTANT_ENCAPSED_STRING => K::LiteralString,
        x if x == c::T_STRING_VARNAME => K::StringVariableName,
        x if x == c::T_NUM_STRING => K::OffsetNumber,
        x if x == c::T_INCLUDE => K::Include,
        x if x == c::T_INCLUDE_ONCE => K::IncludeOnce,
        x if x == c::T_EVAL => K::Eval,
        x if x == c::T_REQUIRE => K::Require,
        x if x == c::T_REQUIRE_ONCE => K::RequireOnce,
        x if x == c::T_LOGICAL_OR => K::Or,
        x if x == c::T_LOGICAL_XOR => K::Xor,
        x if x == c::T_LOGICAL_AND => K::And,
        x if x == c::T_PRINT => K::Print,
        x if x == c::T_YIELD => K::Yield,
        x if x == c::T_YIELD_FROM => K::Yield, // `yield from` — bridge distinguishes by text if needed
        x if x == c::T_INSTANCEOF => K::Instanceof,
        x if x == c::T_NEW => K::New,
        x if x == c::T_CLONE => K::Clone,
        x if x == c::T_EXIT => K::Exit,
        x if x == c::T_IF => K::If,
        x if x == c::T_ELSEIF => K::ElseIf,
        x if x == c::T_ELSE => K::Else,
        x if x == c::T_ENDIF => K::EndIf,
        x if x == c::T_ECHO => K::Echo,
        x if x == c::T_DO => K::Do,
        x if x == c::T_WHILE => K::While,
        x if x == c::T_ENDWHILE => K::EndWhile,
        x if x == c::T_FOR => K::For,
        x if x == c::T_ENDFOR => K::EndFor,
        x if x == c::T_FOREACH => K::Foreach,
        x if x == c::T_ENDFOREACH => K::EndForeach,
        x if x == c::T_DECLARE => K::Declare,
        x if x == c::T_ENDDECLARE => K::EndDeclare,
        x if x == c::T_AS => K::As,
        x if x == c::T_SWITCH => K::Switch,
        x if x == c::T_ENDSWITCH => K::EndSwitch,
        x if x == c::T_CASE => K::Case,
        x if x == c::T_DEFAULT => K::Default,
        x if x == c::T_MATCH => K::Match,
        x if x == c::T_BREAK => K::Break,
        x if x == c::T_CONTINUE => K::Continue,
        x if x == c::T_GOTO => K::Goto,
        x if x == c::T_FUNCTION => K::Function,
        x if x == c::T_FN => K::Fn,
        x if x == c::T_CONST => K::Const,
        x if x == c::T_RETURN => K::Return,
        x if x == c::T_TRY => K::Try,
        x if x == c::T_CATCH => K::Catch,
        x if x == c::T_FINALLY => K::Finally,
        x if x == c::T_THROW => K::Throw,
        x if x == c::T_USE => K::Use,
        x if x == c::T_INSTEADOF => K::Insteadof,
        x if x == c::T_GLOBAL => K::Global,
        x if x == c::T_STATIC => K::Static,
        x if x == c::T_ABSTRACT => K::Abstract,
        x if x == c::T_FINAL => K::Final,
        x if x == c::T_PRIVATE => K::Private,
        x if x == c::T_PROTECTED => K::Protected,
        x if x == c::T_PUBLIC => K::Public,
        x if x == c::T_PRIVATE_SET => K::PrivateSet,
        x if x == c::T_PROTECTED_SET => K::ProtectedSet,
        x if x == c::T_PUBLIC_SET => K::PublicSet,
        x if x == c::T_READONLY => K::Readonly,
        x if x == c::T_VAR => K::Var,
        x if x == c::T_UNSET => K::Unset,
        x if x == c::T_ISSET => K::Isset,
        x if x == c::T_EMPTY => K::Empty,
        x if x == c::T_HALT_COMPILER => K::HaltCompiler,
        x if x == c::T_CLASS => K::Class,
        x if x == c::T_TRAIT => K::Trait,
        x if x == c::T_INTERFACE => K::Interface,
        x if x == c::T_ENUM => K::Enum,
        x if x == c::T_EXTENDS => K::Extends,
        x if x == c::T_IMPLEMENTS => K::Implements,
        x if x == c::T_NAMESPACE => K::Namespace,
        x if x == c::T_LIST => K::List,
        x if x == c::T_ARRAY => K::Array,
        x if x == c::T_CALLABLE => K::Callable,
        x if x == c::T_LINE => K::LineConstant,
        x if x == c::T_FILE => K::FileConstant,
        x if x == c::T_DIR => K::DirConstant,
        x if x == c::T_CLASS_C => K::ClassConstant,
        x if x == c::T_TRAIT_C => K::TraitConstant,
        x if x == c::T_METHOD_C => K::MethodConstant,
        x if x == c::T_FUNC_C => K::FunctionConstant,
        x if x == c::T_PROPERTY_C => K::PropertyConstant,
        x if x == c::T_NS_C => K::NamespaceConstant,
        x if x == c::T_ATTRIBUTE => K::HashLeftBracket,
        x if x == c::T_PLUS_EQUAL => K::PlusEqual,
        x if x == c::T_MINUS_EQUAL => K::MinusEqual,
        x if x == c::T_MUL_EQUAL => K::AsteriskEqual,
        x if x == c::T_DIV_EQUAL => K::SlashEqual,
        x if x == c::T_CONCAT_EQUAL => K::DotEqual,
        x if x == c::T_MOD_EQUAL => K::PercentEqual,
        x if x == c::T_AND_EQUAL => K::AmpersandEqual,
        x if x == c::T_OR_EQUAL => K::PipeEqual,
        x if x == c::T_XOR_EQUAL => K::CaretEqual,
        x if x == c::T_SL_EQUAL => K::LeftShiftEqual,
        x if x == c::T_SR_EQUAL => K::RightShiftEqual,
        x if x == c::T_COALESCE_EQUAL => K::QuestionQuestionEqual,
        x if x == c::T_BOOLEAN_OR => K::PipePipe,
        x if x == c::T_BOOLEAN_AND => K::AmpersandAmpersand,
        x if x == c::T_IS_EQUAL => K::EqualEqual,
        x if x == c::T_IS_NOT_EQUAL => K::BangEqual,
        x if x == c::T_IS_IDENTICAL => K::EqualEqualEqual,
        x if x == c::T_IS_NOT_IDENTICAL => K::BangEqualEqual,
        x if x == c::T_IS_SMALLER_OR_EQUAL => K::LessThanEqual,
        x if x == c::T_IS_GREATER_OR_EQUAL => K::GreaterThanEqual,
        x if x == c::T_SPACESHIP => K::LessThanEqualGreaterThan,
        x if x == c::T_SL => K::LeftShift,
        x if x == c::T_SR => K::RightShift,
        x if x == c::T_INC => K::PlusPlus,
        x if x == c::T_DEC => K::MinusMinus,
        x if x == c::T_INT_CAST => K::IntCast,
        x if x == c::T_DOUBLE_CAST => K::DoubleCast,
        x if x == c::T_STRING_CAST => K::StringCast,
        x if x == c::T_ARRAY_CAST => K::ArrayCast,
        x if x == c::T_OBJECT_CAST => K::ObjectCast,
        x if x == c::T_BOOL_CAST => K::BoolCast,
        x if x == c::T_UNSET_CAST => K::UnsetCast,
        x if x == c::T_VOID_CAST => K::VoidCast,
        x if x == c::T_OBJECT_OPERATOR => K::MinusGreaterThan,
        x if x == c::T_NULLSAFE_OBJECT_OPERATOR => K::QuestionMinusGreaterThan,
        x if x == c::T_DOUBLE_ARROW => K::EqualGreaterThan,
        x if x == c::T_COMMENT => {
            if text.starts_with(b"#") { K::HashComment } else { K::SingleLineComment }
        }
        x if x == c::T_DOC_COMMENT => {
            if text.starts_with(b"/**") { K::DocBlockComment } else { K::MultiLineComment }
        }
        x if x == c::T_OPEN_TAG => K::OpenTag,
        x if x == c::T_OPEN_TAG_WITH_ECHO => K::EchoTag,
        x if x == c::T_CLOSE_TAG => K::CloseTag,
        x if x == c::T_WHITESPACE => K::Whitespace,
        x if x == c::T_START_HEREDOC => K::DocumentStart,
        x if x == c::T_END_HEREDOC => K::DocumentEnd,
        x if x == c::T_DOLLAR_OPEN_CURLY_BRACES => K::DollarLeftBrace,
        x if x == c::T_CURLY_OPEN => K::LeftBrace,
        x if x == c::T_PAAMAYIM_NEKUDOTAYIM => K::ColonColon,
        x if x == c::T_NS_SEPARATOR => K::NamespaceSeparator,
        x if x == c::T_ELLIPSIS => K::DotDotDot,
        x if x == c::T_COALESCE => K::QuestionQuestion,
        x if x == c::T_POW => K::AsteriskAsterisk,
        x if x == c::T_POW_EQUAL => K::AsteriskAsteriskEqual,
        x if x == c::T_PIPE => K::PipeGreaterThan,
        x if x == c::T_AMPERSAND_FOLLOWED_BY_VAR_OR_VARARG => K::Ampersand,
        x if x == c::T_AMPERSAND_NOT_FOLLOWED_BY_VAR_OR_VARARG => K::Ampersand,
        x if x == c::T_DOUBLE_COLON => K::ColonColon,
        x if x == c::T_BAD_CHARACTER => K::BadCharacter,
        _ => K::Identifier, // anything unmapped: treat as a name-ish token
    }
}

/// Is this token a genuinely un-lexable character (`T_BAD_CHARACTER`)? Used by the parser bridge to
/// report "Unexpected character" — semantically, so it never misfires on a valid token whose numeric
/// id happens to collide with the host PHP `T_BAD_CHARACTER` value (the by-ref `&` regression).
#[inline]
pub fn is_bad_character(id: i64, text: &[u8]) -> bool {
    classify(id, text) == TokenKind::BadCharacter
}
