<?php

declare(strict_types=1);

namespace Psalm\Internal;

/**
 * The interned ids (Interner::hash) of the names Psalm's own code refers to: pzoom's generated `StrId`
 * constants. Generated by bin/generate-sym.php; do not edit.
 *
 * @internal
 * @psalm-immutable
 */
final class Sym
{
    /** `` */
    public const EMPTY = 4797691740620326445;
    /** `Closure` */
    public const CLOSURE = 5892975167685871538;
    /** `Traversable` */
    public const TRAVERSABLE = 2510313290758341638;
    /** `Iterator` */
    public const ITERATOR = 8460111478565065076;
    /** `IteratorAggregate` */
    public const ITERATOR_AGGREGATE = 7342470755148473324;
    /** `Throwable` */
    public const THROWABLE = 94831918764527191;
    /** `Exception` */
    public const EXCEPTION = 1479645010934445347;
    /** `Error` */
    public const ERROR = 8013780305775114115;
    /** `stdClass` */
    public const STD_CLASS = 231996262256117584;
    /** `Generator` */
    public const GENERATOR = 2698868278925311619;
    /** `Countable` */
    public const COUNTABLE = 376033948336399582;
    /** `Stringable` */
    public const STRINGABLE = 2556834676045119953;
    /** `self` */
    public const SELF = 2852660938965633389;
    /** `static` */
    public const STATIC = 1335590545988339695;
    /** `parent` */
    public const PARENT = 4231834832957691001;
    /** `__construct` */
    public const CONSTRUCT = 3382564448877090733;
    /** `__destruct` */
    public const DESTRUCT = 5691088208178543058;
    /** `__call` */
    public const CALL = 8628220337170367366;
    /** `__callStatic` */
    public const CALL_STATIC = 1581261718573231335;
    /** `__get` */
    public const GET = 3407561851061190111;
    /** `__set` */
    public const SET = 2767823299192269249;
    /** `__isset` */
    public const ISSET = 2920316239351839102;
    /** `__unset` */
    public const UNSET = 2327073671135115313;
    /** `__sleep` */
    public const SLEEP = 7113730034438234897;
    /** `__wakeup` */
    public const WAKEUP = 1901885556704046983;
    /** `__serialize` */
    public const SERIALIZE = 1679894526645440540;
    /** `__unserialize` */
    public const UNSERIALIZE = 3528718869334508555;
    /** `__toString` */
    public const TO_STRING = 482850270128963222;
    /** `__invoke` */
    public const INVOKE = 1647427323143086741;
    /** `__set_state` */
    public const SET_STATE = 7735846320412266184;
    /** `__clone` */
    public const CLONE = 3143688217959380106;
    /** `__debugInfo` */
    public const DEBUG_INFO = 658687677005025495;
    /** `$this` */
    public const THIS_VAR = 3701023240118791341;
    /** `DOMDocument` */
    public const DOM_DOCUMENT = 3603486196441792353;
    /** `DateTime` */
    public const DATE_TIME = 25147771020527780;
    /** `DateTimeImmutable` */
    public const DATE_TIME_IMMUTABLE = 1515074261426796815;
    /** `DateTimeInterface` */
    public const DATE_TIME_INTERFACE = 89297357357501001;
    /** `MessageFormatter` */
    public const MESSAGE_FORMATTER = 7562163175905339821;
    /** `NumberFormatter` */
    public const NUMBER_FORMATTER = 5010559586850091839;
    /** `ReflectionClass` */
    public const REFLECTION_CLASS = 4227730980695408714;
    /** `ReflectionFunction` */
    public const REFLECTION_FUNCTION = 8215016306427452788;
    /** `SimpleXMLElement` */
    public const SIMPLE_XML_ELEMENT = 2403490401687716580;
    /** `SimpleXMLIterator` */
    public const SIMPLE_XML_ITERATOR = 8725412249255748828;
    /** `__PHP_Incomplete_Class` */
    public const PHP_INCOMPLETE_CLASS = 3774462677534619091;
    /** `ArrayAccess` */
    public const ARRAY_ACCESS = 7431580748819145201;
    /** `ArrayObject` */
    public const ARRAY_OBJECT = 5714570872347613020;
    /** `ArrayIterator` */
    public const ARRAY_ITERATOR = 7248518743032101567;
    /** `UnitEnum` */
    public const UNIT_ENUM = 6477935645783227277;
    /** `BackedEnum` */
    public const BACKED_ENUM = 5713723060064801996;
    /** `SplObjectStorage` */
    public const SPL_OBJECT_STORAGE = 1552938740815837374;
    /** `WeakMap` */
    public const WEAK_MAP = 199556905908489164;
    /** `PDOStatement` */
    public const PDO_STATEMENT = 4048283410091161184;
    /** `DOMNodeList` */
    public const DOM_NODE_LIST = 4675593964523646482;
    /** `DatePeriod` */
    public const DATE_PERIOD = 744302612207116974;
    /** `IteratorIterator` */
    public const ITERATOR_ITERATOR = 8778375353591431299;
    /** `SeekableIterator` */
    public const SEEKABLE_ITERATOR = 4876255212468564893;
    /** `OuterIterator` */
    public const OUTER_ITERATOR = 2714909729678302128;
    /** `RecursiveIterator` */
    public const RECURSIVE_ITERATOR = 4335277008551619673;
    /** `JsonSerializable` */
    public const JSON_SERIALIZABLE = 879831790830110541;
    /** `Serializable` */
    public const SERIALIZABLE = 3828241092641770287;
    /** `callable-object` */
    public const CALLABLE_OBJECT = 7173888424040814020;
    /** `offsetGet` */
    public const OFFSET_GET = 6291830200553730628;
    /** `offsetSet` */
    public const OFFSET_SET = 3793847127950609463;
    /** `offsetExists` */
    public const OFFSET_EXISTS = 6700776040815164872;
    /** `offsetUnset` */
    public const OFFSET_UNSET = 8188928326992791535;
    /** `getIterator` */
    public const GET_ITERATOR = 2573929534014476010;
    /** `count` */
    public const COUNT = 8197783949329762945;
    /** `current` */
    public const CURRENT = 5378696391864791768;
    /** `key` */
    public const KEY = 7162220531701115579;
    /** `next` */
    public const NEXT = 4592796128233508461;
    /** `rewind` */
    public const REWIND = 8901351126678086305;
    /** `valid` */
    public const VALID = 6631373364010963213;
    /** `cases` */
    public const CASES = 2009888848317674150;
    /** `from` */
    public const FROM = 2207122527620866935;
    /** `tryFrom` */
    public const TRY_FROM = 2949545269677071199;
    /** `name` */
    public const NAME = 6158473215981008140;
    /** `value` */
    public const VALUE = 8138177816349824391;
    /** `jsonSerialize` */
    public const JSON_SERIALIZE = 8044460422733846099;
    /** `mixed` */
    public const MIXED = 7922561976114297195;
    /** `iterable` */
    public const ITERABLE = 8387073025668260858;
    /** `callable` */
    public const CALLABLE = 1977547412625762836;
    /** `object` */
    public const OBJECT = 823527073289988991;

    /**
     * The preloaded names, interned at startup so their ids resolve in every process.
     *
     * @var list<string>
     */
    public const PRELOADED = [
        '',
        'Closure',
        'Traversable',
        'Iterator',
        'IteratorAggregate',
        'Throwable',
        'Exception',
        'Error',
        'stdClass',
        'Generator',
        'Countable',
        'Stringable',
        'self',
        'static',
        'parent',
        '__construct',
        '__destruct',
        '__call',
        '__callStatic',
        '__get',
        '__set',
        '__isset',
        '__unset',
        '__sleep',
        '__wakeup',
        '__serialize',
        '__unserialize',
        '__toString',
        '__invoke',
        '__set_state',
        '__clone',
        '__debugInfo',
        '$this',
        'DOMDocument',
        'DateTime',
        'DateTimeImmutable',
        'DateTimeInterface',
        'MessageFormatter',
        'NumberFormatter',
        'ReflectionClass',
        'ReflectionFunction',
        'SimpleXMLElement',
        'SimpleXMLIterator',
        '__PHP_Incomplete_Class',
        'ArrayAccess',
        'ArrayObject',
        'ArrayIterator',
        'UnitEnum',
        'BackedEnum',
        'SplObjectStorage',
        'WeakMap',
        'PDOStatement',
        'DOMNodeList',
        'DatePeriod',
        'IteratorIterator',
        'SeekableIterator',
        'OuterIterator',
        'RecursiveIterator',
        'JsonSerializable',
        'Serializable',
        'callable-object',
        'offsetGet',
        'offsetSet',
        'offsetExists',
        'offsetUnset',
        'getIterator',
        'count',
        'current',
        'key',
        'next',
        'rewind',
        'valid',
        'cases',
        'from',
        'tryFrom',
        'name',
        'value',
        'jsonSerialize',
        'mixed',
        'iterable',
        'callable',
        'object',
    ];
}
